### ISSUE TITLE
dest.end is not a function

### ISSUE THREAD

**Issue by thaiwash** [madshall/screen-streamer#1]
_stream_readable.js:598
    dest.end();
         ^

TypeError: dest.end is not a function
    at Socket.onend (_stream_readable.js:598:10)
    at Object.onceWrapper (events.js:254:19)
    at Socket.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1062:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)

On Win10.

**Comment by thaiwash** [comment]
the other example created 1 png file with no content,

**Comment by madshall** [comment]
@thaiwash can you provide more details on the code you're running? It has never been tested on Windows and I haven't even thought of it to be used on it. It may be an issue with some module used in the package that's incompatible with Windows 10.

**Comment by thaiwash** [comment]
hmm what kinda detail are you looking for? i included the debug traceback.. if you want to look at it together, hit me an email at taivas,gogoljuk@gmail.com

**Comment by thaiwash** [comment]
i just ran the example code

**Comment by madshall** [comment]
It seems to be an issue with a stream not to be writable. What version of node are you running?

**Comment by thaiwash** [comment]
Looks like x11grab is linux only. Ill look into this.

**Comment by madshall** [comment]
Yep, x11grab is linux only. It makes this library linux-compatible only.
